<?php

/**
 * @file
 * Install file for the anati_cr_geo_distribution_migration.
 */

/**
 * Implements hook_uninstall().
 */
function manati_cr_geo_distribution_migration_uninstall() {
  db_query("DELETE FROM {config} WHERE name = 'migrate_plus.migration.cantones_cr'");
  db_query("DELETE FROM {config} WHERE name = 'migrate_plus.migration.distritos_cr'");
  db_query("DELETE FROM {config} WHERE name = 'migrate_plus.migration.provincias_cr'");
  drupal_flush_all_caches();
}
